name: Npm Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Npm Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: https://registry.npmjs.com

      - name: Install Dependencies
        run: pnpm install

      - name: Set Git User Info
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}

      - name: Change Version
        run: |
          pnpm version patch --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          pnpm -r --filter=./packages/* version $VERSION --no-git-tag-version
          git add . && git commit -m "chore(release): publish $VERSION"

      - name: Build and Publish
        run: |
          pnpm run build
          pnpm -r --filter=./packages/* publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          tags: true
